spring:
  application:
    name: item-service
    
#server:
#  port: 8001

#eureka客户端
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka


#item-server集群高可用
---
spring:
  profiles: item1
  
server:
  port: 8001
  
  
---
spring:
  profiles: item2

server:
  port: 8002
